version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../../itse-laptopshop-management-web-application:/workspaces/itse-laptopshop-management-web-application
    
    environment:
      PGPASSWORD: postgres
      ELASTICSEARCH_HOST: elasticsearch

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    depends_on:
      - db
      - elasticsearch
    networks:
      - app-network

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - action.destructive_requires_name=false
    ports:
      - "9200:9200"  # Expose HTTP API
      - "9300:9300"  # Expose internal cluster communication
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - app-network

  logstash:
    build:
      context: ..
      dockerfile: .devcontainer/DockerfileLogstash
    container_name: logstash
    depends_on:
      - db
      - elasticsearch
    ports:
      - "5044:5044"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  elasticsearch-data:
